
---
- 
 hosts: all
 become: True
 gather_facts: True
 tasks:
    - name: Deploying template
      template:
           src: hosts.j2
           dest: /etc/hosts
      
      when: inventory_hostname in  groups['all']
...
